name: 24/7 Telegram JazzDrive Bot

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Engines & Tools
        run: |
          pip install python-telegram-bot yt-dlp playwright nest_asyncio requests
          playwright install chromium
          playwright install-deps chromium

      - name: Start The Bot
        timeout-minutes: 290
        run: python bot.py
